### ISSUE TITLE
Feature Request: inherit timezone from Vagrant env and setup NTP inside VMs

### ISSUE THREAD

**Issue by twillert** [roman-mueller/puppet4-sandbox#2]
Feature Request:

Both VMs do not have any NTP configuration enabled by their (Puppetlabs) Box maintainers. In my timezone they are always 2 hours off, which can be a bit annoying.

What about making them inherit the timezone from the Vagrant environment at provisioning time? With the timezone value it is relatively easy to setup a NTP client to pull time from public NTP servers.

**Comment by roman-mueller** [comment]
There is no need for ntp since the VirtualBox guest additions should keep the time in sync.  

As for setting the right timezone: I'm not sure how to do that.  
There is no such variable as far as I can see, so we'd need to some `timezone=date +%Z` hackery -- which will break compatibility with Windows hosts.
